---
title: "DE_analysis"
author: "Anna Hakobyan"
date: "2023-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = '', fig.width = 6, 
                      fig.height = 6, echo = FALSE, 
                      warning = FALSE)
```


```{r, include=FALSE}
library(here)
library(DESeq2)
library(tidyverse)
library(ggrepel)
library(openxlsx)
library(EnhancedVolcano)
library(fgsea)
library(stringr)
library(ComplexHeatmap)
library(colorRamp2)
library(rstatix)
library(ggsignif)

out.dir = here("outputs")
fig.dir = here("figures")

for (dir in c(out.dir, fig.dir)) {
    if (!exists(dir) ) {
        dir.create(dir)
    }
}

source(here("scripts/functions.R"))

# Functions from menchelab/SA_bone_marrow repository
source("../../SA_bone_marrow/R/functions.R")
source(here("submodule/modulescoring/geneset_modulescoring.R"))
```

### Reading in the data

```{r}
smp.table = read.delim(here("data/samples_quantseq_SAHDME23.csv"), sep = ",")

smp.table = smp.table %>%
    mutate(cell.type = gsub("(.*)__(.*)", "\\1", Condition_ID),
           treatment = gsub("(.*)__(.*)", "\\2", Condition_ID))

cell.types = unique(smp.table$cell.type)

counts.raw = read.delim(here("data/rnaseq_deseq_global_counts_raw.tsv"))
colnames(counts.raw) = gsub("(MR_54_[0-9]*)_S.*", "\\1", colnames(counts.raw))

gene.data = counts.raw[, 1:8]
```

### DESeq2 for all the cell types 

```{r, message = FALSE, echo = FALSE, include = FALSE}
ct.res = list()
for (ct in cell.types) {
    
    cat("DESeq2 for ", ct, "\n")
    
    ct.res[[ct]] = get_celltype_DEseq2(ct, counts.raw, smp.table, min.gene.counts = 3)
    
    ct.res[[ct]]$res_df = as.data.frame(ct.res[[ct]]$res) %>% 
        rownames_to_column(var = "gene_id") %>% 
        left_join(., gene.data %>% select(gene_id, gene_name), by = "gene_id") %>% 
        select(gene_name, baseMean, log2FoldChange, lfcSE, pvalue, padj)
}
```

```{r}

DE.files.xlsx = file.path(out.dir, "DE.genes.SAvsPBS.xlsx")

if (!file.exists(DE.files.xlsx)) {
    wb <- createWorkbook()
}else {
    wb = loadWorkbook(filename)
}

for (ct in cell.types) {
    addWorksheet(wb, ct)
    
    writeData(wb = wb,
              sheet = ct,
              x = ct.res[[ct]]$res_df %>% arrange(padj),
              colNames = TRUE,
              rowNames = FALSE)
}

saveWorkbook(wb, file = DE.files.xlsx, overwrite = TRUE)

add_mouse_geneinfo(DE.files.xlsx)
```

### Making the volcano plots

```{r}
for (ct in cell.types) {
    
    res.out = ct.res[[ct]]$res
    lab.names = ct.res[[ct]]$res %>% 
        as.data.frame %>% 
        rownames_to_column(var = "gene_id") %>% 
        dplyr::left_join (., gene.data %>% dplyr::select(gene_id, gene_name) ,
                                                 by = "gene_id") %>% pull(gene_name)
    
    pp = EnhancedVolcano(res.out,
        lab = lab.names,
        x = 'log2FoldChange',
        y = 'pvalue',
        title = paste0(ct, " SA vs PBS"),
        pCutoff = 0.05,
        FCcutoff = 1,
        pointSize = 3.0,
        labSize = 6.0,
        col=c('black', 'black', 'black', 'red3'),
        colAlpha = 1)
        ggsave(plot = pp, filename = file.path(fig.dir, paste0(ct,".SAvsPBS․Volcano_h7.pdf")),
               width = 7, height = 7)
}

for (ct in cell.types) {
    
    res.out = ct.res[[ct]]$res
    lab.names = ct.res[[ct]]$res %>% 
        as.data.frame %>% 
        rownames_to_column(var = "gene_id") %>% 
        dplyr::left_join (., gene.data %>% dplyr::select(gene_id, gene_name) ,
                                                 by = "gene_id") %>% pull(gene_name)
    
    pp = EnhancedVolcano(res.out,
        lab = lab.names,
        x = 'log2FoldChange',
        y = 'pvalue',
        title = paste0(ct, " SA vs PBS"),
        pCutoff = 0.05,
        FCcutoff = 1,
        pointSize = 3.0,
        labSize = 6.0,
        col=c('black', 'black', 'black', 'red3'),
        colAlpha = 1)
        ggsave(plot = pp, filename = file.path(fig.dir, paste0(ct,".SAvsPBS․Volcano_h9.pdf")),
               width = 7, height = 9)
}
```

### Heatmaps of DEGs 

```{r}
center_apply <- function(x) {
    out = t(apply(x, 1, function(y) y - mean(y)))
    rownames(out) = rownames(x)
    colnames(out) = colnames(x)
    
    return(out)
}

for (ct in cell.types) {
    
    rld = rlog (ct.res[[ct]]$dds)

    # DE.genes = ct.res[[ct]]$res %>% as.data.frame() %>%
    #     rownames_to_column("gene") %>%
    #     filter(padj < 0.05, abs(log2FoldChange) > 1.8 ) %>% pull(gene)

    
    DE.genes = ct.res[[ct]]$res %>% as.data.frame() %>%
        rownames_to_column("gene") %>%
        filter(padj < 0.05) %>% 
        arrange(-abs(log2FoldChange)) %>%
        head(n = 50) %>% pull(gene)

    
    lab.names = DE.genes %>% 
        enframe(value = "gene_id") %>% 
        dplyr::left_join (., gene.data %>% dplyr::select(gene_id, gene_name) ,
                                                 by = "gene_id") %>% pull(gene_name)
    
    mat = assay(rld)[DE.genes, ]
    
    mat.centered = center_apply(mat)
    
    rownames(mat.centered) = lab.names
    
    rdbu.palette = colorRamp2(c(quantile(mat.centered, 0.01), 0, quantile(mat.centered, 0.99)), 
                          c("dodgerblue4", "white", "darkred"), space = "RGB")
    
    clust.ht.rdbu = Heatmap(mat.centered[sort(rownames(mat.centered)), ], name = "expression", 
            col = rdbu.palette,
            column_split = rld$treatment,
            top_annotation = HeatmapAnnotation(cluster = anno_block(
        gp = gpar(fill = c("grey", "goldenrod1"), col = "white"), # <- here controls the filled color
        ) ),
            column_names_gp = gpar(fontsize = 0),
        cluster_rows = FALSE,
        cluster_column_slices = FALSE, 
        row_dend_width = unit(0, "cm"),
        column_dend_height = unit(0, "cm"),
        row_dend_gp = gpar(col = "white"),
        column_dend_gp = gpar(col = "white") )
    
    # pwidth = 4
    # pheight = length(DE.genes) / 12 + 4.8
    
    # if (ct == "Eosinophil_progenitor") {pheight = pheight + 4}
    
    pwidth = 3.5
    pheight = 12
    
    if (any(grepl("ENSMUS", DE.genes))) {
        pwidth = pwidth + 2
    }
    
    pdf(here(file.path(fig.dir, paste0(ct,".SAvsPBS.Heatmap.pdf"))), 
        width = pwidth, height = pheight)
    draw(clust.ht.rdbu)
    dev.off()
    
}
```


### FGSEA analysis 

```{r}
gene.sets = list()

for (gene.set.paths in list.files(here("data/gene_sets"), full.names = TRUE, pattern = "txt")) {
    file.base = basename(gene.set.paths)
    
    gene.sets[[file.base]] = read_gene_sets(gene.set.paths)
}
```


```{r}
fgsea.set = list()

for (ct in cell.types) {
    ranks = setNames(ct.res[[ct]]$res$log2FoldChange, ct.res[[ct]]$res_df$gene_name)
    names(rafnks) = convert_mouse_to_human(names(ranks))

    cell.type.gseas = list()
    
    for(gene.set in names(gene.sets)) {
        
        fgseaRes <- fgsea(gene.sets[[gene.set]], ranks, minSize = 20, maxSize=500)    
        cell.type.gseas[[gene.set]] = fgseaRes    
        
    }
    fgsea.set[[ct]] = cell.type.gseas
}

```

```{r}

filtered.fgsea = list()
for (ct in cell.types) {
    
    cell.type.gseas = list()
    for(gene.set in names(gene.sets)) {
        cell.type.gseas[[gene.set]] = fgsea.set[[ct]][[gene.set]] %>% 
            filter(pval < 0.05) %>% arrange(pval, ES)
    }
    filtered.fgsea[[ct]] = cell.type.gseas
  
    write_excel_allsheets(filtered.fgsea[[ct]], file.path(out.dir, paste0( ct, ".SAvsPBS.FGSEA.xlsx")) )
}

saveRDS(filtered.fgsea, file = file.path(out.dir, "DE.list.FGSEA.RDS"))
# filtered.fgsea = readRDS(file = file.path(out.dir, "DE.list.FGSEA.RDS"))
```

```{r}
for (ct in cell.types) {
    for (gset in names(filtered.fgsea[[ct]])) {
        
        path.number = filtered.fgsea[[ct]][[gset]] %>%
            
            mutate(pathway = gsub(" \\(GO:.*\\)", "", pathway)) %>% 
            filter(pval < 0.05) %>% nrow
        
        if (path.number)
        pp =  filtered.fgsea[[ct]][[gset]] %>%
            mutate(pathway = gsub(" \\(GO:.*\\)", "", pathway),
                   pathway = gsub(" (PMID.*)$", "", pathway),
                   pathway = gsub(" (GSE.*)$", "", pathway)) %>% 
            filter(pval < 0.05) %>% 
            ggplot(aes(y = pathway, x = 1, size = -log10(pval), color = ES)) + 
            geom_point() + scale_color_gradient2(low = scales::muted("blue"), high = scales::muted("red")) + 
            scale_x_continuous(expand = c(0.1, 0.1)) +
            scale_y_discrete(labels = function(x) str_wrap(x, width = 100) ) +
            theme_bw() + 
            theme(axis.title.x = element_blank(),
                  axis.text.x = element_blank(),
                  axis.ticks.x = element_blank(),
                  panel.grid.major.x = element_blank(),
                  panel.grid.minor.x = element_blank())
        
        ggsave(filename = file.path(fig.dir, paste(ct, gset, "fgsea.pdf", sep = ".")),
               plot = pp,
               width = 8, height = path.number / 8 + 2)
    }
}

```


### Get DEG score for cell types

```{r}
# The adaptation of GeneModuleScore for DeSeq2 object is here: 
# https://github.com/HerpelinckT/geneset-modulescoring?tab=readme-ov-file

source(here("submodule/modulescoring/geneset_modulescoring.R"))
```

```{r}
gene_list = gene.sets$GO_Biological_Process_2021.txt$`antigen processing and presentation of exogenous peptide antigen via MHC class II (GO:0019886)`

gene_list = list( 
    NFkB = gene.sets$GO_Biological_Process_2021.txt$`regulation of NIK/NF-kappaB signaling (GO:1901222)`,
    chemotaxis = gene.sets$GO_Biological_Process_2021.txt$`cell chemotaxis (GO:0060326)`,
    cell_cycle = gene.sets$GO_Biological_Process_2021.txt$`positive regulation of cell cycle process (GO:0090068)`,
    protein_phosphorylation = gene.sets$GO_Biological_Process_2021.txt$`positive regulation of protein phosphorylation (GO:0001934)`,
    mhc2_antigen_PP = gene.sets$GO_Biological_Process_2021.txt$`antigen processing and presentation of peptide antigen via MHC class II (GO:0002495)`,
    cell_division = gene.sets$GO_Biological_Process_2021.txt$`positive regulation of cell division (GO:0051781)`,
    sensecence = gene.sets$GO_Biological_Process_2021.txt$`cellular senescence (GO:0090398)`,
    glucose_metabolism = gene.sets$GO_Biological_Process_2021.txt$`glucose metabolic process (GO:0006006)`,
    stress_response_transcription = gene.sets$GO_Biological_Process_2021.txt$`positive regulation of transcription from RNA polymerase II promoter in response to stress (GO:0036003)`,
    actin_filament_polymerization = gene.sets$GO_Biological_Process_2021.txt$`regulation of actin filament polymerization (GO:0030833)`,
    ubiquitin_dependent_protein_catabolism = gene.sets$GO_Biological_Process_2021.txt$`proteasome-mediated ubiquitin-dependent protein catabolic process (GO:0043161)`
    )

path_names = c(NFkB = "regulation of NIK/NF-kappaB signaling",
    chemotaxis = "cell chemotaxis",
    cell_cycle = "positive regulation of cell cycle process",
    protein_phosphorylation = "positive regulation of protein phosphorylation",
    mhc2_antigen_PP = "antigen processing and presentation of peptide antigen via MHC class II",
    cell_division = "positive regulation of cell division",
    sensecence = "cellular senescence",
    glucose_metabolism = "glucose metabolic process",
    stress_response_transcription = "positive regulation of transcription from RNA polymerase II promoter in response to stress",
    actin_filament_polymerization = "regulation of actin filament polymerization",
    ubiquitin_dependent_protein_catabolism = "proteasome-mediated ubiquitin-dependent protein catabolic process"
    )



ct.gss = list()

for (ct in names(ct.res)) {
    
    dds_rownames_hgnc = rownames(ct.res[[ct]]$dds) %>% 
        enframe(value = "gene_id") %>% 
        left_join(., gene.data %>% select(gene_id, gene_name), by = "gene_id") %>% 
        pull(gene_name)
    
    dds_copy = ct.res[[ct]]$dds

    ct.gss[[ct]] = dds_copy@colData
    
    rownames(dds_copy) = dds_rownames_hgnc
    
    for (gl_name in names(gene_list) ) {
    
        mouse_gene_list = convert_human_to_mouse(gene_list[[gl_name]])

        dds_added = AddGeneSetScore(dds = dds_copy, mouse_gene_list[,2], name = gl_name)
        
        ct.gss[[ct]][gl_name] = colData(dds_added)[paste0(gl_name, "1")]
    }
}
```



```{r}


for (tname in c("t.test", "wilcox.test") ) {
    for (ct in names(ct.gss)) {
        dd = ct.gss[[ct]]
        
        pp = dd %>% as_tibble() %>% 
            select(c(treatment, NFkB:ubiquitin_dependent_protein_catabolism) ) %>% 
            pivot_longer(cols = !treatment, names_to = "geneset", values_to = "score") %>% 
            mutate(path = path_names[geneset]) %>% 
            ggplot(aes (x = treatment, y = score)) + 
            geom_boxplot(aes(fill = treatment)) + geom_jitter() + 
            facet_wrap(~path, labeller = label_wrap_gen() ) +
            theme_bw() + 
            scale_fill_manual(values = c("PBS" = "grey", "SA" = "goldenrod1")) + 
            geom_signif(comparisons = list(c("PBS", "SA")), 
                        map_signif_level=TRUE, test = tname,  margin_top = 0.1) + 
            scale_y_continuous(limits = c(0, 1.2), breaks = seq(0, 1, 0.25))
        
        ggsave(plot = pp, filename = file.path(
            fig.dir, paste(ct, tname, "modulescoring.pdf", sep = ".")),
            width = 8, height = 7)
    }
}
```

### Cytopus scoring

```{r}
gene_list = gene.sets$cytopus_processes.txt

ct.gss.cyto = list()

for (ct in names(ct.res)) {
    
    dds_rownames_hgnc = rownames(ct.res[[ct]]$dds) %>% 
        enframe(value = "gene_id") %>% 
        left_join(., gene.data %>% select(gene_id, gene_name), by = "gene_id") %>% 
        pull(gene_name)
    
    dds_copy = ct.res[[ct]]$dds

    ct.gss.cyto[[ct]] = dds_copy@colData
    
    rownames(dds_copy) = dds_rownames_hgnc
    
    for (gl in names(gene_list) ) {
        # cat(gl_name, "\n")

        mouse_gene_list = convert_human_to_mouse(gene_list[[gl]])

        gl_name = gsub("[_-]", ".", gl)
        
        
        try({
            dds_added = AddGeneSetScore(dds = dds_copy, mouse_gene_list[,2], name = gl_name)
            ct.gss.cyto[[ct]][gl_name] = colData(dds_added)[paste0(gl_name, "1")]
            })
        
    }
}

```

### Saving the cytopus files

```{r}
wb = openxlsx::createWorkbook()

for (ct in names(ct.gss.cyto)) {
    
    cat(ct, "\n")
    
    sheetname = openxlsx::addWorksheet(wb = wb, sheetName = ct)
    
    openxlsx::writeData(wb = wb,
              sheet = sheetname,
              x = ct.gss.cyto[[ct]] %>% as_tibble(),
              colNames = TRUE,
              rowNames = FALSE)
    
}

openxlsx::saveWorkbook(wb = wb, file = file.path(here("outputs"), "cytopus_genescoring.xlsx"), overwrite = TRUE )

```

```{r}
for (tname in c("t.test", "wilcox.test") ) {
    
    for (ct in names(ct.gss.cyto)) {
        dd = ct.gss.cyto[[ct]]
        
        dd.pivot = dd %>% as.data.frame() %>% 
            select(c(treatment, 8:ncol(.))) %>% 
            pivot_longer(cols = !treatment, names_to = "geneset", values_to = "score") # %>% 
            # mutate(geneset = gsub(".", " ", geneset, fixed = TRUE))
        
        
        if (tname == "t.test") {
            
            sig.gss = dd.pivot %>% 
                group_by(geneset) %>% 
                wilcox_test(score ~ treatment) %>%
                adjust_pvalue(method = "BH") %>%
                add_significance("p") %>%
                add_significance("p.adj") %>%
                filter(p.adj < 0.1)
            
            
        } else if (tname == "wilcox.test") {
            
             sig.gss = dd.pivot %>% 
                group_by(geneset) %>% 
                t_test(score ~ treatment) %>%
                adjust_pvalue(method = "BH") %>%
                add_significance("p.adj") %>% 
                filter(p.adj < 0.1)
            
        }
        
        if (nrow(sig.gss) == 0) {next}
        
        pp = dd %>% as_tibble() %>% 
            select(c(treatment, sig.gss$geneset) ) %>% 
            pivot_longer(cols = !treatment, names_to = "geneset", values_to = "score") %>% 
            mutate(geneset_name = gsub(".", " ", geneset, fixed = TRUE)) %>% 
            ggplot(aes (x = treatment, y = score)) + 
            geom_boxplot(aes(fill = treatment)) + geom_jitter(width = 0.25) + 
            facet_wrap(~geneset_name, labeller = label_wrap_gen() ) +
            theme_bw() + 
            scale_fill_manual(values = c("PBS" = "grey", "SA" = "goldenrod1")) + 
            geom_signif(comparisons = list(c("PBS", "SA")), 
                        map_signif_level=TRUE, test = tname,  margin_top = 0.1) + 
            scale_y_continuous(limits = c(0, 1.2), breaks = seq(0, 1, 0.25))
        
        ggsave(plot = pp, filename = file.path(
            fig.dir, paste(ct, tname, "modulescoring.cytopus_geneset.pdf", sep = ".")),
            width = 12, height = 10)
    }
    
}
```


### Getting the emaplot

```{r}
library(clusterProfiler)
library(org.Mm.eg.db)
library(enrichplot)
library(RColorBrewer)
library(viridis)

genes = ct.res$Eosinophil$res_df$gene_name


# Perform enrichment analysis
# Here, I'm using Gene Ontology (GO) enrichment as an example
ego <- enrichGO(gene         = genes,
                OrgDb        = org.Mm.eg.db, # Replace with the appropriate OrgDb for your organism
                keyType      = "SYMBOL",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.2,
                readable     = TRUE)

# Calculate term similarity matrix
similarity_matrix <- pairwise_termsim(ego)

# Create the emaplot
emap_plot = clusterProfiler::emapplot(similarity_matrix, showCategory=20) + scale_color_viridis()

pp = emap_plot + scale_fill_viridis(labels = scales::scientific)



for (ct in names(ct.res)) {
    cat(ct, "\n")
    genes = ct.res[[ct]]$res_df$gene_name
    ego <- enrichGO(gene         = genes,
                OrgDb        = org.Mm.eg.db, # Replace with the appropriate OrgDb for your organism
                keyType      = "SYMBOL",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.2,
                readable     = TRUE)

    # Calculate term similarity matrix
    similarity_matrix <- pairwise_termsim(ego)
    
    # Create the emaplot
    emap_plot = clusterProfiler::emapplot(similarity_matrix, showCategory=20) + scale_color_viridis()
    
    pp = emap_plot + scale_fill_viridis(direction = -1, labels = scales::scientific)
    
    ggsave(here(file.path(fig.dir, paste0(ct,".SAvsPBS.emapplot.pdf"))), 
        width = 8, height = 6)
}
```


### PCA for all the samples

```{r}
counts.mat = as.matrix(counts.raw[, 9:ncol(counts.raw)])
rdata = counts.raw[, 1:8]
cdata = smp.table %>% filter(Sample_Name %in% colnames(counts.mat)) 

se = SummarizedExperiment(assays = counts.mat, 
                          rowData = rdata,
                          colData = cdata)

dds_all = DESeqDataSet(se, design= ~ treatment)
normed = rlog(dds_all)
```

### PCA for the cell types separately

```{r}

N = 1000  ### top variable genes

for (ct in unique(normed$cell.type)) {
    ct_normed = normed[, normed$cell.type == ct]
    
    rv <- rowVars(assay(ct_normed))
    select <- order(rv, decreasing=TRUE)[seq_len(min(N, length(rv)))]
    
    # perform a PCA on the data in assay(x) for the selected genes
    pca <- prcomp(t(assay(ct_normed)[select,]))
    
    # the contribution to the total variance for each component
    percentVar <- pca$sdev^2 / sum( pca$sdev^2 )
    
    sample_pca = pca$x %>% as.data.frame() %>%
        mutate(treatment = ct_normed$treatment) %>% 
        ggplot(aes(x = PC1, y = PC2, color = treatment)) +
        geom_point(size = 3) + 
        xlab(paste0("PC1: ",round(percentVar[1] * 100),"% variance")) +
        ylab(paste0("PC2: ",round(percentVar[2] * 100),"% variance")) +
        coord_fixed() + 
        theme_classic() +
        # scale_color_manual(values = "#FFFFFF") + 
        scale_color_manual(values = c("PBS" = "grey", "SA" = "goldenrod1"))
    
    # scale_shape_manual(values = c("PBS" = 16, "SA" = 17) ) +
     
    ggsave(here(file.path(fig.dir, paste0(ct,".SAvsPBS.PCA.pdf"))), 
        width = 4, height = 2.5)  
}


```


```{r}

pca.data = plotPCA(normed, intgroup = c("treatment", "cell.type"), returnData = TRUE)

############################## beware!!!!! The percentages are hardcoded now
sample_pca = ggplot(data = pca.data, aes(x = PC1, y = PC2, color = cell.type, shape = treatment)) +
     geom_point(size = 3) + 
    xlab(paste0("PC1: 40% variance")) +
      ylab(paste0("PC2: 6% variance")) +
        coord_fixed() + 
        theme_classic() +
    # scale_color_manual(values = "#FFFFFF") + 
    scale_color_brewer(palette = "Dark2",
                      labels = c("Eosinophil" = "Eosinophil", 
                                  "Neutrophil" = "Neutrophil", 
                                  "Neutrophil_progenitor" = "Neutrophil progenitor", 
                                  "Eosinophil_progenitor" = "Eosinophil progenitor", 
                                  "Granulocyte_Monocyte_progenitor" ="GMP",
                                  "Common_Myeloid_progenitor" ="CMP")) +
        
    scale_shape_manual(values = c("PBS" = 16, "SA" = 17) )
    # scale_shape_manual(values = c("PBS" = 16, "SA" = 17) ) +
    
ggsave(here(file.path(fig.dir, "allSamplePCA_pca_dark2cols.pdf")), width = 6, height = 4.5)

sample_pca = ggplot(data = pca.data, aes(x = PC1, y = PC2, color = cell.type, shape = treatment)) +
     geom_point(size = 3) + 
    xlab(paste0("PC1: 40% variance")) +
      ylab(paste0("PC2: 6% variance")) +
        coord_fixed() + 
        theme_classic() +
    scale_color_discrete("Set1",
                      labels = c("Eosinophil" = "Eosinophil", 
                                  "Neutrophil" = "Neutrophil", 
                                  "Neutrophil_progenitor" = "Neutrophil progenitor", 
                                  "Eosinophil_progenitor" = "Eosinophil progenitor", 
                                  "Granulocyte_Monocyte_progenitor" ="GMP",
                                  "Common_Myeloid_progenitor" ="CMP")) +
        
    scale_shape_manual(values = c("PBS" = 16, "SA" = 17) )
    # scale_shape_manual(values = c("PBS" = 16, "SA" = 17) ) +
    
ggsave(here(file.path(fig.dir, "allSamplePCA_umapcolors.pdf")), width = 6, height = 4.5)
```

